name: bengilchriest
favicon: null
layout_spectrum: 0.20287737087346613
typography_spectrum: 0.040956317679956555
title: Ben Gilchriest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6530379687901586
  lightness: 0.1267477162182331
  saturation: 0.32628881232813
  rhythmicContrast: 0.9696426114533097
purpose: []
